name: pybarsim

channels:
  - conda-forge
  - defaults

dependencies:
  - python
  - pip
  - numpy
  - scipy
  - numba
  - matplotlib
  - xarray
  - pyvista
  - pip:
    - git+https://github.com/grongier/pybarsim.git
